// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/gitlab-org/api/client-go"
)

// NewGitLabGroups creates a new instance of GitLabGroups. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitLabGroups(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitLabGroups {
	mock := &GitLabGroups{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitLabGroups is an autogenerated mock type for the GitLabGroups type
type GitLabGroups struct {
	mock.Mock
}

type GitLabGroups_Expecter struct {
	mock *mock.Mock
}

func (_m *GitLabGroups) EXPECT() *GitLabGroups_Expecter {
	return &GitLabGroups_Expecter{mock: &_m.Mock}
}

// ListGroupProjects provides a mock function for the type GitLabGroups
func (_mock *GitLabGroups) ListGroupProjects(gid interface{}, opt *gitlab.ListGroupProjectsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Project, *gitlab.Response, error) {
	// gitlab.RequestOptionFunc
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, gid, opt)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupProjects")
	}

	var r0 []*gitlab.Project
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, *gitlab.ListGroupProjectsOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.Project, *gitlab.Response, error)); ok {
		return returnFunc(gid, opt, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, *gitlab.ListGroupProjectsOptions, ...gitlab.RequestOptionFunc) []*gitlab.Project); ok {
		r0 = returnFunc(gid, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, *gitlab.ListGroupProjectsOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(gid, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(interface{}, *gitlab.ListGroupProjectsOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(gid, opt, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GitLabGroups_ListGroupProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroupProjects'
type GitLabGroups_ListGroupProjects_Call struct {
	*mock.Call
}

// ListGroupProjects is a helper method to define mock.On call
//   - gid interface{}
//   - opt *gitlab.ListGroupProjectsOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *GitLabGroups_Expecter) ListGroupProjects(gid interface{}, opt interface{}, options ...interface{}) *GitLabGroups_ListGroupProjects_Call {
	return &GitLabGroups_ListGroupProjects_Call{Call: _e.mock.On("ListGroupProjects",
		append([]interface{}{gid, opt}, options...)...)}
}

func (_c *GitLabGroups_ListGroupProjects_Call) Run(run func(gid interface{}, opt *gitlab.ListGroupProjectsOptions, options ...gitlab.RequestOptionFunc)) *GitLabGroups_ListGroupProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 *gitlab.ListGroupProjectsOptions
		if args[1] != nil {
			arg1 = args[1].(*gitlab.ListGroupProjectsOptions)
		}
		var arg2 []gitlab.RequestOptionFunc
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *GitLabGroups_ListGroupProjects_Call) Return(projects []*gitlab.Project, response *gitlab.Response, err error) *GitLabGroups_ListGroupProjects_Call {
	_c.Call.Return(projects, response, err)
	return _c
}

func (_c *GitLabGroups_ListGroupProjects_Call) RunAndReturn(run func(gid interface{}, opt *gitlab.ListGroupProjectsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Project, *gitlab.Response, error)) *GitLabGroups_ListGroupProjects_Call {
	_c.Call.Return(run)
	return _c
}
