// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"bytes"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/gitlab-org/api/client-go"
)

// NewGitLabJobs creates a new instance of GitLabJobs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitLabJobs(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitLabJobs {
	mock := &GitLabJobs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitLabJobs is an autogenerated mock type for the GitLabJobs type
type GitLabJobs struct {
	mock.Mock
}

type GitLabJobs_Expecter struct {
	mock *mock.Mock
}

func (_m *GitLabJobs) EXPECT() *GitLabJobs_Expecter {
	return &GitLabJobs_Expecter{mock: &_m.Mock}
}

// DownloadArtifactsFile provides a mock function for the type GitLabJobs
func (_mock *GitLabJobs) DownloadArtifactsFile(pid interface{}, refName string, opt *gitlab.DownloadArtifactsFileOptions, options ...gitlab.RequestOptionFunc) (*bytes.Reader, *gitlab.Response, error) {
	// gitlab.RequestOptionFunc
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, refName, opt)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DownloadArtifactsFile")
	}

	var r0 *bytes.Reader
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, string, *gitlab.DownloadArtifactsFileOptions, ...gitlab.RequestOptionFunc) (*bytes.Reader, *gitlab.Response, error)); ok {
		return returnFunc(pid, refName, opt, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, string, *gitlab.DownloadArtifactsFileOptions, ...gitlab.RequestOptionFunc) *bytes.Reader); ok {
		r0 = returnFunc(pid, refName, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, string, *gitlab.DownloadArtifactsFileOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(pid, refName, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(interface{}, string, *gitlab.DownloadArtifactsFileOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(pid, refName, opt, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GitLabJobs_DownloadArtifactsFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadArtifactsFile'
type GitLabJobs_DownloadArtifactsFile_Call struct {
	*mock.Call
}

// DownloadArtifactsFile is a helper method to define mock.On call
//   - pid interface{}
//   - refName string
//   - opt *gitlab.DownloadArtifactsFileOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *GitLabJobs_Expecter) DownloadArtifactsFile(pid interface{}, refName interface{}, opt interface{}, options ...interface{}) *GitLabJobs_DownloadArtifactsFile_Call {
	return &GitLabJobs_DownloadArtifactsFile_Call{Call: _e.mock.On("DownloadArtifactsFile",
		append([]interface{}{pid, refName, opt}, options...)...)}
}

func (_c *GitLabJobs_DownloadArtifactsFile_Call) Run(run func(pid interface{}, refName string, opt *gitlab.DownloadArtifactsFileOptions, options ...gitlab.RequestOptionFunc)) *GitLabJobs_DownloadArtifactsFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *gitlab.DownloadArtifactsFileOptions
		if args[2] != nil {
			arg2 = args[2].(*gitlab.DownloadArtifactsFileOptions)
		}
		var arg3 []gitlab.RequestOptionFunc
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *GitLabJobs_DownloadArtifactsFile_Call) Return(reader *bytes.Reader, response *gitlab.Response, err error) *GitLabJobs_DownloadArtifactsFile_Call {
	_c.Call.Return(reader, response, err)
	return _c
}

func (_c *GitLabJobs_DownloadArtifactsFile_Call) RunAndReturn(run func(pid interface{}, refName string, opt *gitlab.DownloadArtifactsFileOptions, options ...gitlab.RequestOptionFunc) (*bytes.Reader, *gitlab.Response, error)) *GitLabJobs_DownloadArtifactsFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobArtifacts provides a mock function for the type GitLabJobs
func (_mock *GitLabJobs) GetJobArtifacts(pid interface{}, jobID int64, options ...gitlab.RequestOptionFunc) (*bytes.Reader, *gitlab.Response, error) {
	// gitlab.RequestOptionFunc
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, jobID)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetJobArtifacts")
	}

	var r0 *bytes.Reader
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, int64, ...gitlab.RequestOptionFunc) (*bytes.Reader, *gitlab.Response, error)); ok {
		return returnFunc(pid, jobID, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, int64, ...gitlab.RequestOptionFunc) *bytes.Reader); ok {
		r0 = returnFunc(pid, jobID, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, int64, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(pid, jobID, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(interface{}, int64, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(pid, jobID, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GitLabJobs_GetJobArtifacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobArtifacts'
type GitLabJobs_GetJobArtifacts_Call struct {
	*mock.Call
}

// GetJobArtifacts is a helper method to define mock.On call
//   - pid interface{}
//   - jobID int64
//   - options ...gitlab.RequestOptionFunc
func (_e *GitLabJobs_Expecter) GetJobArtifacts(pid interface{}, jobID interface{}, options ...interface{}) *GitLabJobs_GetJobArtifacts_Call {
	return &GitLabJobs_GetJobArtifacts_Call{Call: _e.mock.On("GetJobArtifacts",
		append([]interface{}{pid, jobID}, options...)...)}
}

func (_c *GitLabJobs_GetJobArtifacts_Call) Run(run func(pid interface{}, jobID int64, options ...gitlab.RequestOptionFunc)) *GitLabJobs_GetJobArtifacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []gitlab.RequestOptionFunc
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *GitLabJobs_GetJobArtifacts_Call) Return(reader *bytes.Reader, response *gitlab.Response, err error) *GitLabJobs_GetJobArtifacts_Call {
	_c.Call.Return(reader, response, err)
	return _c
}

func (_c *GitLabJobs_GetJobArtifacts_Call) RunAndReturn(run func(pid interface{}, jobID int64, options ...gitlab.RequestOptionFunc) (*bytes.Reader, *gitlab.Response, error)) *GitLabJobs_GetJobArtifacts_Call {
	_c.Call.Return(run)
	return _c
}

// ListPipelineJobs provides a mock function for the type GitLabJobs
func (_mock *GitLabJobs) ListPipelineJobs(pid interface{}, pipelineID int64, opts *gitlab.ListJobsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Job, *gitlab.Response, error) {
	// gitlab.RequestOptionFunc
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, pipelineID, opts)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListPipelineJobs")
	}

	var r0 []*gitlab.Job
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, int64, *gitlab.ListJobsOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.Job, *gitlab.Response, error)); ok {
		return returnFunc(pid, pipelineID, opts, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, int64, *gitlab.ListJobsOptions, ...gitlab.RequestOptionFunc) []*gitlab.Job); ok {
		r0 = returnFunc(pid, pipelineID, opts, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, int64, *gitlab.ListJobsOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(pid, pipelineID, opts, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(interface{}, int64, *gitlab.ListJobsOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(pid, pipelineID, opts, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GitLabJobs_ListPipelineJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPipelineJobs'
type GitLabJobs_ListPipelineJobs_Call struct {
	*mock.Call
}

// ListPipelineJobs is a helper method to define mock.On call
//   - pid interface{}
//   - pipelineID int64
//   - opts *gitlab.ListJobsOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *GitLabJobs_Expecter) ListPipelineJobs(pid interface{}, pipelineID interface{}, opts interface{}, options ...interface{}) *GitLabJobs_ListPipelineJobs_Call {
	return &GitLabJobs_ListPipelineJobs_Call{Call: _e.mock.On("ListPipelineJobs",
		append([]interface{}{pid, pipelineID, opts}, options...)...)}
}

func (_c *GitLabJobs_ListPipelineJobs_Call) Run(run func(pid interface{}, pipelineID int64, opts *gitlab.ListJobsOptions, options ...gitlab.RequestOptionFunc)) *GitLabJobs_ListPipelineJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *gitlab.ListJobsOptions
		if args[2] != nil {
			arg2 = args[2].(*gitlab.ListJobsOptions)
		}
		var arg3 []gitlab.RequestOptionFunc
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *GitLabJobs_ListPipelineJobs_Call) Return(jobs []*gitlab.Job, response *gitlab.Response, err error) *GitLabJobs_ListPipelineJobs_Call {
	_c.Call.Return(jobs, response, err)
	return _c
}

func (_c *GitLabJobs_ListPipelineJobs_Call) RunAndReturn(run func(pid interface{}, pipelineID int64, opts *gitlab.ListJobsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Job, *gitlab.Response, error)) *GitLabJobs_ListPipelineJobs_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjectJobs provides a mock function for the type GitLabJobs
func (_mock *GitLabJobs) ListProjectJobs(pid interface{}, opts *gitlab.ListJobsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Job, *gitlab.Response, error) {
	// gitlab.RequestOptionFunc
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, opts)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListProjectJobs")
	}

	var r0 []*gitlab.Job
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, *gitlab.ListJobsOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.Job, *gitlab.Response, error)); ok {
		return returnFunc(pid, opts, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, *gitlab.ListJobsOptions, ...gitlab.RequestOptionFunc) []*gitlab.Job); ok {
		r0 = returnFunc(pid, opts, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, *gitlab.ListJobsOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(pid, opts, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(interface{}, *gitlab.ListJobsOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(pid, opts, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GitLabJobs_ListProjectJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjectJobs'
type GitLabJobs_ListProjectJobs_Call struct {
	*mock.Call
}

// ListProjectJobs is a helper method to define mock.On call
//   - pid interface{}
//   - opts *gitlab.ListJobsOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *GitLabJobs_Expecter) ListProjectJobs(pid interface{}, opts interface{}, options ...interface{}) *GitLabJobs_ListProjectJobs_Call {
	return &GitLabJobs_ListProjectJobs_Call{Call: _e.mock.On("ListProjectJobs",
		append([]interface{}{pid, opts}, options...)...)}
}

func (_c *GitLabJobs_ListProjectJobs_Call) Run(run func(pid interface{}, opts *gitlab.ListJobsOptions, options ...gitlab.RequestOptionFunc)) *GitLabJobs_ListProjectJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 *gitlab.ListJobsOptions
		if args[1] != nil {
			arg1 = args[1].(*gitlab.ListJobsOptions)
		}
		var arg2 []gitlab.RequestOptionFunc
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *GitLabJobs_ListProjectJobs_Call) Return(jobs []*gitlab.Job, response *gitlab.Response, err error) *GitLabJobs_ListProjectJobs_Call {
	_c.Call.Return(jobs, response, err)
	return _c
}

func (_c *GitLabJobs_ListProjectJobs_Call) RunAndReturn(run func(pid interface{}, opts *gitlab.ListJobsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Job, *gitlab.Response, error)) *GitLabJobs_ListProjectJobs_Call {
	_c.Call.Return(run)
	return _c
}
