// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/gitlab-org/api/client-go"
)

// NewGitLabProjects creates a new instance of GitLabProjects. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitLabProjects(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitLabProjects {
	mock := &GitLabProjects{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitLabProjects is an autogenerated mock type for the GitLabProjects type
type GitLabProjects struct {
	mock.Mock
}

type GitLabProjects_Expecter struct {
	mock *mock.Mock
}

func (_m *GitLabProjects) EXPECT() *GitLabProjects_Expecter {
	return &GitLabProjects_Expecter{mock: &_m.Mock}
}

// ListProjects provides a mock function for the type GitLabProjects
func (_mock *GitLabProjects) ListProjects(opt *gitlab.ListProjectsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Project, *gitlab.Response, error) {
	// gitlab.RequestOptionFunc
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, opt)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListProjects")
	}

	var r0 []*gitlab.Project
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*gitlab.ListProjectsOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.Project, *gitlab.Response, error)); ok {
		return returnFunc(opt, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(*gitlab.ListProjectsOptions, ...gitlab.RequestOptionFunc) []*gitlab.Project); ok {
		r0 = returnFunc(opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gitlab.ListProjectsOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(*gitlab.ListProjectsOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(opt, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GitLabProjects_ListProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjects'
type GitLabProjects_ListProjects_Call struct {
	*mock.Call
}

// ListProjects is a helper method to define mock.On call
//   - opt *gitlab.ListProjectsOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *GitLabProjects_Expecter) ListProjects(opt interface{}, options ...interface{}) *GitLabProjects_ListProjects_Call {
	return &GitLabProjects_ListProjects_Call{Call: _e.mock.On("ListProjects",
		append([]interface{}{opt}, options...)...)}
}

func (_c *GitLabProjects_ListProjects_Call) Run(run func(opt *gitlab.ListProjectsOptions, options ...gitlab.RequestOptionFunc)) *GitLabProjects_ListProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gitlab.ListProjectsOptions
		if args[0] != nil {
			arg0 = args[0].(*gitlab.ListProjectsOptions)
		}
		var arg1 []gitlab.RequestOptionFunc
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *GitLabProjects_ListProjects_Call) Return(projects []*gitlab.Project, response *gitlab.Response, err error) *GitLabProjects_ListProjects_Call {
	_c.Call.Return(projects, response, err)
	return _c
}

func (_c *GitLabProjects_ListProjects_Call) RunAndReturn(run func(opt *gitlab.ListProjectsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Project, *gitlab.Response, error)) *GitLabProjects_ListProjects_Call {
	_c.Call.Return(run)
	return _c
}
