// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/gitlab-org/api/client-go"
)

// NewGitLabPipelines creates a new instance of GitLabPipelines. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitLabPipelines(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitLabPipelines {
	mock := &GitLabPipelines{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitLabPipelines is an autogenerated mock type for the GitLabPipelines type
type GitLabPipelines struct {
	mock.Mock
}

type GitLabPipelines_Expecter struct {
	mock *mock.Mock
}

func (_m *GitLabPipelines) EXPECT() *GitLabPipelines_Expecter {
	return &GitLabPipelines_Expecter{mock: &_m.Mock}
}

// GetLatestPipeline provides a mock function for the type GitLabPipelines
func (_mock *GitLabPipelines) GetLatestPipeline(pid interface{}, opt *gitlab.GetLatestPipelineOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Pipeline, *gitlab.Response, error) {
	// gitlab.RequestOptionFunc
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, opt)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestPipeline")
	}

	var r0 *gitlab.Pipeline
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, *gitlab.GetLatestPipelineOptions, ...gitlab.RequestOptionFunc) (*gitlab.Pipeline, *gitlab.Response, error)); ok {
		return returnFunc(pid, opt, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, *gitlab.GetLatestPipelineOptions, ...gitlab.RequestOptionFunc) *gitlab.Pipeline); ok {
		r0 = returnFunc(pid, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.Pipeline)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, *gitlab.GetLatestPipelineOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(pid, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(interface{}, *gitlab.GetLatestPipelineOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(pid, opt, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GitLabPipelines_GetLatestPipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestPipeline'
type GitLabPipelines_GetLatestPipeline_Call struct {
	*mock.Call
}

// GetLatestPipeline is a helper method to define mock.On call
//   - pid interface{}
//   - opt *gitlab.GetLatestPipelineOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *GitLabPipelines_Expecter) GetLatestPipeline(pid interface{}, opt interface{}, options ...interface{}) *GitLabPipelines_GetLatestPipeline_Call {
	return &GitLabPipelines_GetLatestPipeline_Call{Call: _e.mock.On("GetLatestPipeline",
		append([]interface{}{pid, opt}, options...)...)}
}

func (_c *GitLabPipelines_GetLatestPipeline_Call) Run(run func(pid interface{}, opt *gitlab.GetLatestPipelineOptions, options ...gitlab.RequestOptionFunc)) *GitLabPipelines_GetLatestPipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 *gitlab.GetLatestPipelineOptions
		if args[1] != nil {
			arg1 = args[1].(*gitlab.GetLatestPipelineOptions)
		}
		var arg2 []gitlab.RequestOptionFunc
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *GitLabPipelines_GetLatestPipeline_Call) Return(pipeline *gitlab.Pipeline, response *gitlab.Response, err error) *GitLabPipelines_GetLatestPipeline_Call {
	_c.Call.Return(pipeline, response, err)
	return _c
}

func (_c *GitLabPipelines_GetLatestPipeline_Call) RunAndReturn(run func(pid interface{}, opt *gitlab.GetLatestPipelineOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Pipeline, *gitlab.Response, error)) *GitLabPipelines_GetLatestPipeline_Call {
	_c.Call.Return(run)
	return _c
}
