all: true
log-level: info
structname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/steffakasid/trivy-scanner/internal:
    config:
      dir: internal/mocks
      recursive: true
